### PR TITLE
ISO 8601 support

### PR DESCRIPTION
**Pull request by tcanich**
These changes add new functions, isoweekdayLong and isoweekdayShort, as well as tests for both functions.  The purpose of the functions is to return the long and short weekday names when using ISO 8601 ordered day numbers from isoweekday.

Also, a small change to configure.ac to correct a syntax failure when executing configure.  The error was noted with aclocal 1.15 and autoreconf 2.69.  No testing was done with other versions of these tools.

### CODE REVIEW

**Comment by tcanich** [comment]
@milancurcic 881219e may not be needed if you are moving away from autotools to cmake.  I didn't notice this change until I'd already committed to my fork and submitted the PR.

0f29b21 was intended to bring my fork up to date (in an effort to avoid the previous) and I didn't intend it to be included in this PR...I'm still a bit clumsy with github.

Thank you very much for datetime-fortran!

**Comment by milancurcic** [comment]
Thanks @tcanich, I have reviewed this and all looks OK. :+1:  

About the build system, my plan was to keep both autotools and cmake as valid build options.

**Comment by zbeekman** [comment]
> About the build system, my plan was to keep both autotools and cmake as valid build options.

bold move!

**Comment by milancurcic** [comment]
@zbeekman I am curious about your comment - anything I am not aware of? I was convinced that autotools and cmake are completely independent of each other and can co-exist happily, no?

**Comment by zbeekman** [comment]
Yes they certainly can, but now you have two build systems to update and
keep in sync... I didn't mean to alarm you, but I find that one build
system is a PITA enough to maintain as it is already, let alone two!

**Comment by milancurcic** [comment]
@zbeekman OK, thanks, I thought that was what you had in mind. 

I doubt that we will be adding many more source files to datetime-fortran in the future so maintaining this should be easy. If it turns out not to be, we will abandon autotools.

**Pull request merged**
